version: "3.8"
services:
  chat-log:
    build:
      context: ./src/ChatLogService
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=appdb;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
      - NATS__ConnectionString=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats

  chat-moderation:
    build:
      context: ./src/ChatModerationService
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=appdb;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
      - NATS__ConnectionString=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats

  emoji-log:
    build:
      context: ./src/EmojiLogService
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=appdb;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
      - NATS__ConnectionString=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats

  emoji-favorites:
    build:
      context: ./src/EmojiFavoritesService
      dockerfile: Dockerfile
    ports:
      - "8084:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=appdb;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
      - NATS__ConnectionString=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats

  emoji-bomb:
    build:
      context: ./src/EmojiBombService
      dockerfile: Dockerfile
    ports:
      - "8085:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=appdb;Username=postgres;Password=postgres
      - Redis__ConnectionString=redis:6379
      - NATS__ConnectionString=nats://nats:4222
    depends_on:
      - postgres
      - redis
      - nats

  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - deps

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - deps

  nats:
    image: nats:2.10-alpine
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP management port
    volumes:
      - nats_data:/root/.local/share/nats
    healthcheck:
      test: ["CMD", "nats-server", "--ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles:
      - deps

volumes:
  postgres_data:
  redis_data:
  nats_data:
